services:
  - type: web
    name: helpdesk-api
    runtime: python
    buildCommand: cd helpdesk && pip install -r requirements.txt
    startCommand: cd helpdesk && gunicorn helpdesk_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FIREBASE_CREDENTIALS
        sync: false
